name: Terraform AWS

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: Terraform init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform plan
        run: terraform plan -var-file="variables.tfvars"
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -var-file="variables.tfvars" -auto-approve
        working-directory: ./terraform
      
      - name: Terraform Destroy
        run: terraform destroy -var-file="variables.tfvars" -auto-approve
        working-directory: ./terraform